version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /elaborate
    groups:
      rust:
        patterns:
          - "*"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct

  - package-ecosystem: cargo
    directory: /generate
    groups:
      rust:
        patterns:
          - "*"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
