[package]
name = "ci"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.23"

[dev-dependencies]
assert_cmd = "2.2"
regex = "1.13"
snapbox = "1.2"
tempfile = "3.27"
toml = "1.1"
walkdir = "2.5"

elaborate = { path = "../elaborate" }

[lints]
workspace = true
